version: 0.0
os: linux
runas: app

files:
  - source: /
    destination: /app/
    overwrite: true

hooks:

  ApplicationStop:
    - location: scripts/stop_script.sh
      timeout: 300
      runas: app
  ApplicationStart:
    - location: scripts/start_script.sh
      timeout: 300
      runas: app
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: app
